### ISSUE TITLE
배포시 https에서의 api 요청이 막히는 오류

### ISSUE THREAD

**Issue by sdj799** [project-wins/react-wins#58]
## 어떤 버그인가요?

> 배포시 https에서의 api 요청이 막히는 오류가 발생하여 api요청이 제대로 이루어지지 않음.

## 어떤 상황에서 발생한 버그인가요?

> 배포환경(https://react-wins.vercel.app)에서의 http요청이 막혀 원하는 데이터를 패칭할 수 없음.
> https에 요청을 해도 따로 https로 개발하지 않아 오류가 발생함

## 예상 결과

> proxy 설정을 통해 http로 요청을 하면 버그가 해결 될 것으로 보임.

## 참고할만한 자료(선택)
Mixed Content: The page at 'https://react-wins.vercel.app/player/coach' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://[BASE_URL]/api/player/coachlist'. This request has been blocked; the content must be served over HTTPS.

**Comment by mya413** [comment]
캡쳐 내 서버주소가 노출되어있습니다!! 이미지 수정해주세요!
